name: CI Pipeline

on:
  schedule:
    # Planifier l'exécution tous les jours à 5h du matin heure française (3h UTC en hiver, 3h UTC en été)
    - cron: '0 3 * * *' # 3h UTC (c'est 5h en France toute l'année)
  workflow_dispatch: # Permet de lancer manuellement le workflow si nécessaire

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install selenium pandas requests
        fi

    - name: Install Google Chrome
      run: |
        sudo apt update
        sudo apt install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt --fix-broken install

    - name: Run the script
      run: |
        python main.py
