name: Automate NHL Predictions

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Exécution quotidienne

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Étape pour installer les dépendances Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape pour télécharger ChromeDriver
      - name: Download ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}')
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION} || echo "latest")
          wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      # Autres étapes (par exemple, exécuter des tests, déployer, etc.)
      - name: Run tests
        run: |
          pytest tests/
