name: Scraper Betclever Data

on:
  schedule:
    - cron: '0 3 * * *'  # Exécution à 4h heure française en hiver (CET, UTC+1)
    - cron: '0 2 * * *'  # Exécution à 4h heure française en été (CEST, UTC+2)
  push:
    branches:
      - main

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          # Install Google Chrome
          sudo apt-get install -y google-chrome-stable
          # Get the current version of Chrome installed
          CHROME_VERSION=$(google-chrome --version | sed 's/[^0-9]*\([0-9]*\.[0-9]*\.[0-9]*\).[0-9]*/\1/')
          echo "Chrome version is $CHROME_VERSION"
          # Try downloading the ChromeDriver that matches the Chrome version
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "ChromeDriver version not found for Chrome version $CHROME_VERSION. Trying a fallback version."
            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          fi
          echo "Downloading ChromeDriver version $CHROMEDRIVER_VERSION"
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Verify Chrome and ChromeDriver installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run the scraper
        run: |
          python main.py
