name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Remplacez par la version souhaitée

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install selenium pandas requests  # Liste des packages manquants
        fi

    - name: Run tests
      run: |
        pytest  # ou toute autre commande pour tester votre code

    # Vous pouvez ajouter des étapes supplémentaires si nécessaire
